version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
  jdbc-sync:
    build:
      context: .
    image: dodevza/logstash-jdbc
    volumes:
      - ./config:/usr/share/logstash/config/
      - ./pipelines:/usr/share/logstash/pipeline/
      - logstashdata:/mnt/data
    networks:
      - esnet
  mssql:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: l*gStash_Test
      MSSQL_PID: Express
    ports:
      - 5605:1433
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  mssqldata:
    driver: local
  logstashdata:
    driver: local
networks:
  esnet: